/* AUTO-GENERATED from dishes.json - do not edit by hand.
   129 dishes; key = sorted ingredient ids joined by +. v: yummy|magical|yucky */
const DISH_CATALOG = {
  "apple": {n:"Apple Squish Sauce", v:"yummy"},
  "banana": {n:"Mushy Banana Mash", v:"yummy"},
  "berry": {n:"Strawberry Squish Jam", v:"yummy"},
  "egg": {n:"Wobbly Egg Custard", v:"yummy"},
  "choco": {n:"Choco Goo Pudding", v:"yummy"},
  "cookie": {n:"Giant Cookie Mush", v:"yummy"},
  "icecream": {n:"Melty Ice-Cream Mountain", v:"yummy"},
  "worm": {n:"Wormy Wiggle Noodles", v:"yucky"},
  "rainbow": {n:"Sparkle Rainbow Soup", v:"magical"},
  "apple+banana": {n:"Sunny Fruit Smoothie", v:"yummy"},
  "apple+berry": {n:"Berry-Apple Jelly", v:"yummy"},
  "apple+egg": {n:"Apple Custard Cup", v:"yummy"},
  "apple+choco": {n:"Choco-Dunked Apple", v:"yummy"},
  "apple+cookie": {n:"Grandma's Apple Pie", v:"yummy"},
  "apple+icecream": {n:"Apple Pie a la Mode", v:"yummy"},
  "apple+worm": {n:"Wiggly Apple Wormhole", v:"yucky"},
  "apple+rainbow": {n:"Rainbow Apple Fizz", v:"magical"},
  "banana+berry": {n:"Pink Monkey Smoothie", v:"yummy"},
  "banana+egg": {n:"Banana Pancakes", v:"yummy"},
  "banana+choco": {n:"Choco-Banana Pops", v:"yummy"},
  "banana+cookie": {n:"Banana Cookie Stack", v:"yummy"},
  "banana+icecream": {n:"Banana Split", v:"yummy"},
  "banana+worm": {n:"Wiggle-Waggle Banana Slime", v:"yucky"},
  "banana+rainbow": {n:"Rainbow Banana Dream", v:"magical"},
  "berry+egg": {n:"Strawberry Custard Cup", v:"yummy"},
  "berry+choco": {n:"Strawberry-Choco Cake", v:"yummy"},
  "berry+cookie": {n:"Strawberry Cookie Crumble", v:"yummy"},
  "berry+icecream": {n:"Strawberry Sundae", v:"yummy"},
  "berry+worm": {n:"Wormy Berry Sludge", v:"yucky"},
  "berry+rainbow": {n:"Rainbow Berry Sparkle", v:"magical"},
  "choco+egg": {n:"Chocolate Birthday Cake", v:"yummy"},
  "cookie+egg": {n:"Beepo Burger", v:"yummy"},
  "egg+icecream": {n:"Frozen Custard Swirl", v:"yummy"},
  "egg+worm": {n:"Slimy Worm Scramble", v:"yucky"},
  "egg+rainbow": {n:"Rainbow Cloud Omelette", v:"magical"},
  "choco+cookie": {n:"Double-Choc Donut", v:"yummy"},
  "choco+icecream": {n:"Choco Swirl Cone", v:"yummy"},
  "choco+worm": {n:"Choco-Dipped Wigglers", v:"yucky"},
  "choco+rainbow": {n:"Magic Choco Rainbow Swirl", v:"magical"},
  "cookie+icecream": {n:"Ice-Cream Sandwich", v:"yummy"},
  "cookie+worm": {n:"Wiggly Worm Burger", v:"yucky"},
  "cookie+rainbow": {n:"Rainbow Sprinkle Cookie", v:"magical"},
  "icecream+worm": {n:"Wormy Ice Scream", v:"yucky"},
  "icecream+rainbow": {n:"Rainbow Sparkle Sundae", v:"magical"},
  "rainbow+worm": {n:"Sparkly Rainbow Worm Goo", v:"yucky"},
  "apple+banana+berry": {n:"Tutti-Frutti Salad", v:"yummy"},
  "apple+banana+egg": {n:"Apple-Banana-Egg Yum-Bowl", v:"yummy"},
  "apple+banana+choco": {n:"Apple-Banana-Chocolate Medley", v:"yummy"},
  "apple+banana+cookie": {n:"Triple Treat: Apple, Banana & Cookie", v:"yummy"},
  "apple+banana+icecream": {n:"Apple-Banana-Ice Cream Mash-Up", v:"yummy"},
  "apple+banana+worm": {n:"Apple & Banana Worm Swamp Stew", v:"yucky"},
  "apple+banana+rainbow": {n:"Magical Apple & Banana Shimmer", v:"magical"},
  "apple+berry+egg": {n:"Apple-Strawberry-Egg Medley", v:"yummy"},
  "apple+berry+choco": {n:"Triple Treat: Apple, Strawberry & Chocolate", v:"yummy"},
  "apple+berry+cookie": {n:"Apple-Strawberry-Cookie Mash-Up", v:"yummy"},
  "apple+berry+icecream": {n:"Chef's Apple-Strawberry-Ice Cream Surprise", v:"yummy"},
  "apple+berry+worm": {n:"Squirmy Apple & Strawberry Mush", v:"yucky"},
  "apple+berry+rainbow": {n:"Apple & Strawberry Rainbow Delight", v:"magical"},
  "apple+choco+egg": {n:"Apple-Egg-Chocolate Mash-Up", v:"yummy"},
  "apple+cookie+egg": {n:"Chef's Apple-Egg-Cookie Surprise", v:"yummy"},
  "apple+egg+icecream": {n:"Apple-Egg-Ice Cream Yum-Bowl", v:"yummy"},
  "apple+egg+worm": {n:"Wiggly Apple & Egg Sludge", v:"yucky"},
  "apple+egg+rainbow": {n:"Enchanted Apple & Egg Twinkle Treat", v:"magical"},
  "apple+choco+cookie": {n:"Apple-Chocolate-Cookie Yum-Bowl", v:"yummy"},
  "apple+choco+icecream": {n:"Apple-Chocolate-Ice Cream Medley", v:"yummy"},
  "apple+choco+worm": {n:"Wormy Apple & Chocolate Surprise", v:"yucky"},
  "apple+choco+rainbow": {n:"Rainbow Apple & Chocolate Sparkle Dream", v:"magical"},
  "apple+cookie+icecream": {n:"Apple Pie a la Mode Deluxe", v:"yummy"},
  "apple+cookie+worm": {n:"Slimy Apple & Cookie Wriggle-Goo", v:"yucky"},
  "apple+cookie+rainbow": {n:"Magical Apple & Cookie Shimmer", v:"magical"},
  "apple+icecream+worm": {n:"Apple & Ice Cream Worm Swamp Stew", v:"yucky"},
  "apple+icecream+rainbow": {n:"Apple & Ice Cream Rainbow Delight", v:"magical"},
  "apple+rainbow+worm": {n:"Wiggly Apple Sludge", v:"yucky"},
  "banana+berry+egg": {n:"Triple Treat: Banana, Strawberry & Egg", v:"yummy"},
  "banana+berry+choco": {n:"Banana-Strawberry-Chocolate Mash-Up", v:"yummy"},
  "banana+berry+cookie": {n:"Chef's Banana-Strawberry-Cookie Surprise", v:"yummy"},
  "banana+berry+icecream": {n:"Double-Berry Banana Split", v:"yummy"},
  "banana+berry+worm": {n:"Wiggly Banana & Strawberry Sludge", v:"yucky"},
  "banana+berry+rainbow": {n:"Enchanted Banana & Strawberry Twinkle Treat", v:"magical"},
  "banana+choco+egg": {n:"Choco-Banana Birthday Cake", v:"yummy"},
  "banana+cookie+egg": {n:"Banana-Egg-Cookie Yum-Bowl", v:"yummy"},
  "banana+egg+icecream": {n:"Banana-Egg-Ice Cream Medley", v:"yummy"},
  "banana+egg+worm": {n:"Wormy Banana & Egg Surprise", v:"yucky"},
  "banana+egg+rainbow": {n:"Rainbow Banana & Egg Sparkle Dream", v:"magical"},
  "banana+choco+cookie": {n:"Banana-Chocolate-Cookie Medley", v:"yummy"},
  "banana+choco+icecream": {n:"Choco-Banana Split Supreme", v:"yummy"},
  "banana+choco+worm": {n:"Slimy Banana & Chocolate Wriggle-Goo", v:"yucky"},
  "banana+choco+rainbow": {n:"Magical Banana & Chocolate Shimmer", v:"magical"},
  "banana+cookie+icecream": {n:"Banana Cookie Sundae", v:"yummy"},
  "banana+cookie+worm": {n:"Banana & Cookie Worm Swamp Stew", v:"yucky"},
  "banana+cookie+rainbow": {n:"Banana & Cookie Rainbow Delight", v:"magical"},
  "banana+icecream+worm": {n:"Squirmy Banana & Ice Cream Mush", v:"yucky"},
  "banana+icecream+rainbow": {n:"Enchanted Banana & Ice Cream Twinkle Treat", v:"magical"},
  "banana+rainbow+worm": {n:"Wormy Banana Surprise", v:"yucky"},
  "berry+choco+egg": {n:"Strawberry-Egg-Chocolate Yum-Bowl", v:"yummy"},
  "berry+cookie+egg": {n:"Strawberry-Egg-Cookie Medley", v:"yummy"},
  "berry+egg+icecream": {n:"Triple Treat: Strawberry, Egg & Ice Cream", v:"yummy"},
  "berry+egg+worm": {n:"Slimy Strawberry & Egg Wriggle-Goo", v:"yucky"},
  "berry+egg+rainbow": {n:"Magical Strawberry & Egg Shimmer", v:"magical"},
  "berry+choco+cookie": {n:"Triple Treat: Strawberry, Chocolate & Cookie", v:"yummy"},
  "berry+choco+icecream": {n:"Strawberry-Choco Sundae", v:"yummy"},
  "berry+choco+worm": {n:"Strawberry & Chocolate Worm Swamp Stew", v:"yucky"},
  "berry+choco+rainbow": {n:"Strawberry & Chocolate Rainbow Delight", v:"magical"},
  "berry+cookie+icecream": {n:"Strawberry Shortcake Sundae", v:"yummy"},
  "berry+cookie+worm": {n:"Squirmy Strawberry & Cookie Mush", v:"yucky"},
  "berry+cookie+rainbow": {n:"Enchanted Strawberry & Cookie Twinkle Treat", v:"magical"},
  "berry+icecream+worm": {n:"Wiggly Strawberry & Ice Cream Sludge", v:"yucky"},
  "berry+icecream+rainbow": {n:"Rainbow Strawberry & Ice Cream Sparkle Dream", v:"magical"},
  "berry+rainbow+worm": {n:"Slimy Strawberry Wriggle-Goo", v:"yucky"},
  "choco+cookie+egg": {n:"Chocolate-Chip Cookie Cake", v:"yummy"},
  "choco+egg+icecream": {n:"Chef's Egg-Chocolate-Ice Cream Surprise", v:"yummy"},
  "choco+egg+worm": {n:"Squirmy Egg & Chocolate Mush", v:"yucky"},
  "choco+egg+rainbow": {n:"Enchanted Egg & Chocolate Twinkle Treat", v:"magical"},
  "cookie+egg+icecream": {n:"Egg-Cookie-Ice Cream Yum-Bowl", v:"yummy"},
  "cookie+egg+worm": {n:"Wiggly Egg & Cookie Sludge", v:"yucky"},
  "cookie+egg+rainbow": {n:"Rainbow Egg & Cookie Sparkle Dream", v:"magical"},
  "egg+icecream+worm": {n:"Wormy Egg & Ice Cream Surprise", v:"yucky"},
  "egg+icecream+rainbow": {n:"Magical Egg & Ice Cream Shimmer", v:"magical"},
  "egg+rainbow+worm": {n:"Egg Worm Swamp Stew", v:"yucky"},
  "choco+cookie+icecream": {n:"Cookies-and-Cream Sundae", v:"yummy"},
  "choco+cookie+worm": {n:"Wormy Chocolate & Cookie Surprise", v:"yucky"},
  "choco+cookie+rainbow": {n:"Magical Chocolate & Cookie Shimmer", v:"magical"},
  "choco+icecream+worm": {n:"Slimy Chocolate & Ice Cream Wriggle-Goo", v:"yucky"},
  "choco+icecream+rainbow": {n:"Chocolate & Ice Cream Rainbow Delight", v:"magical"},
  "choco+rainbow+worm": {n:"Squirmy Chocolate Mush", v:"yucky"},
  "cookie+icecream+worm": {n:"Cookie & Ice Cream Worm Swamp Stew", v:"yucky"},
  "cookie+icecream+rainbow": {n:"Enchanted Cookie & Ice Cream Twinkle Treat", v:"magical"},
  "cookie+rainbow+worm": {n:"Wiggly Cookie Sludge", v:"yucky"},
  "icecream+rainbow+worm": {n:"Wormy Ice Cream Surprise", v:"yucky"}
};
